config/routes.rb
ArmoredTruck::Application.routes.draw do
  devise_for :users
  root "main#index"

  get "main/index"
  resources :safes
  resources :users
  resources :keys

  post 'safe/upload' => 'safes#upload'
  post 'safe/decrypt' => 'safes#decrypt'
  get 'user/generate' => 'users#generate'
  post 'key/generate' => 'keys#generate'
end

app/models/key.rb
class Key < ActiveRecord::Base
  belongs_to :user
end

app/models/safe.rb
class Safe < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :safes
  has_many :keys

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  def index
    #specifies the current_user to display keys
    @user = current_user
    #creates a blank key so the form works in the view
    @key = @user.keys.new()
    #creates a list of keys for display to the user
    @keys = Key.where("user_id = ?", @user.id)
  end

  def create
    #specifies the current user for key creation
    @user = current_user
    #specifies all keys associated with a user so that they can be
    #displayed using ajax to the users key table
    @keys = Key.where("user_id = ?", @user.id)
    #creates a new key using the name provided in the form
    @key = @user.keys.create(key_params)
    #responds to ajax request
    respond_to do |format|
      format.html { redirect_to keys_path }
      format.js
    end
  end

def show
  # finds the key to show
  @key = Key.find(params[:id])
end

  def generate
    #specifies curent user so it can be used by @key
    @user = current_user
    #finds the key name to generate a keypair for
    @key = @user.keys.find(params[:key])
    #creates a private key
    private = RbNaCl::PrivateKey.generate
    #creates a public key for the private key
    public = private.public_key
    #writes the public key to the database
    @key.public_key = public.to_bytes
    #saves the key
    @key.save
    #sends private key to the user as a download so that it is never stored server side
    send_data private, :filename => "#{@key.name}"
  end

  #defines accepted parameters
  def key_params
    params.require(:key).permit(:name, :id)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
before_filter :authenticate_user!
  def index
  end
end

app/controllers/safes_controller.rb
class SafesController < ApplicationController
before_filter :authenticate_user!

def index
  #specifies current user so that only that users safes are shown
  @user = current_user
  @safes = Safe.where("user_id = ?", @user.id)
end

def new
  #prepares a new safe under the current_user
  @user = current_user
  @safe = @user.safes.new()
end

def create
  #creates a new safe under the current user
  @user = current_user
  @safe = @user.safes.create(safe_params)
  redirect_to safes_path
end

def show
  #shows a safe by the id. Logic in the view will prevent unauthorized safe views
  @safe = Safe.find(params[:id])
  @users = User.all
end

def update
  @safe = Safe.find(params[:id])
  redirect_to safes_path
end

def upload
  @user = current_user
  @recipient = User.find_by(email: params[:recipient][:recipient_id])
  @key = @recipient.keys.where("name = ?", params[:key_name])
  uploaded_io = params[:safe][:rawfile]
  priv_key = params[:safe][:priv_key]

    box = RbNaCl::Box.new(@key.first.public_key, priv_key.read)
    nonce = RbNaCl::Random.random_bytes(box.nonce_bytes)
    message = uploaded_io.read
    ciphertext = box.encrypt(nonce,message)
    full = nonce + ciphertext
    FileMailer.mail_file(@recipient.email, current_user.email, params[:key_name], priv_key.original_filename, uploaded_io.original_filename).deliver
  send_data full, :filename => uploaded_io.original_filename

end

def decrypt
  @user = current_user
  @sender = User.find_by(email: params[:sender][:sender_id])
  @key = @sender.keys.where("name = ?", params[:key_name])
  uploaded_io = params[:safe][:rawfile]
  priv_key = params[:safe][:priv_key]
    box = RbNaCl::Box.new(@key.first.public_key, priv_key.read)
    ciphertext = uploaded_io.read
    message = box.decrypt(ciphertext.slice(0,24),ciphertext.slice(24,ciphertext.length))
  send_data message, :filename => uploaded_io.original_filename
end

private
def safe_params
  params.require(:safe).permit(:name, :description, :rawfile, :noncefile)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @keys = @user.keys.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/safes_helper.rb
module SafesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/keys/_form.html.erb
<%= form_for(@key, :remote => true) do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.button :submit, :class => "btn btn-xs btn-success" %>
<%end%>

app/views/keys/_index.html.erb
<table class="table table-bordered table-striped">
<tbody>
  <% @keys.each do |key| %>
<tr>
  <td class="col-sm-2"><%= link_to(key.name, key) %></td>
  <td class="col-sm-2"><%= button_to "Generate", key_generate_path(:key => key), :class => "btn btn-sm btn-success", :method => :post ,
  :data => { :confirm => "Generating new keys will break the ability to decrypt any files previously created with this key, are you sure you want to create new keys?"} %>
  </td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/keys/create.js.erb
$("#key_div").html("<%= escape_javascript(render 'index').html_safe %>");
$("#key_name").val("");

app/views/keys/index.html.erb
<div class="col-md-8">
<div id="form_div">
<%= render 'form' %>
</div>
<div id="key_div">
<%= render 'index' %>
</div>
</div>

app/views/keys/new.html.erb
<%= render 'form' %>

app/views/keys/show.html.erb
<h1><%= @key.name %></h1><p>
Key Owner: <%= @key.user.email %><br>
Public Key String: <%= @key.public_key.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ArmoredTruck" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= image_tag "armored_trucknv.png", size: "100", :class => "navbar-brand brand"%>
          <%= link_to "ArmoredTruck", root_path, :class => "navbar-brand brand"%>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Safes", safes_path %></li>
              <li><%= link_to "Keys", keys_path %></li>
              <% end %>
            </ul>
            <% if user_signed_in? %>
            <ul class="nav navbar-right">
              <%= link_to "Sign Out", destroy_user_session_path, { :method => 'delete', :class => "btn btn-sm btn-info navbar-btn" }%>
            </ul>
            <% else %>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <% if user_signed_in? %>
              <li class="nav-header"><%= current_user.email %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
              <%else%>
              <li>Not Signed in</li>
              <%end%>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; @relotnek 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/main/index.html.erb
<h1>Welcome to Armored Truck!</h1>
<p>Armored truck provides a way to quickly and easily encrypt files for sending</p>

app/views/safes/_decrypt.html.erb
<%= form_for(@safe, :url => safe_decrypt_path, :method => 'post') do |f| %>
	<%= f.label "Your Private Key:" %><br>
	<%= f.file_field :priv_key %>
	<%= f.label "Encrypted File:" %>
	<%= f.file_field :rawfile %><br>
	<%= label_tag "Sender Email:" %><br>
	<%= select("sender","sender_id", @users.all.collect {|s| [ s.email, s.email ]}) %><br>
	<%= label_tag "Name of the sender's public key:" %><br>
	<%= text_field_tag :key_name %><br>
<%= f.button :submit, :class => "btn btn-xs btn-success" %>
<% end %>

app/views/safes/_form.html.erb
<%= form_for(@safe) do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :description %><br>
<%= f.text_field :description %><br>
<%= f.button :submit, :class => "btn btn-xs btn-success" %>
<%end%>

app/views/safes/_upload.html.erb
<%= form_for(@safe, :url => safe_upload_path, :method => 'post') do |f| %>
	<%= f.label "Your Private Key:" %><br>
	<%= f.file_field :priv_key %>
	<%= f.label "File to Encrypt:" %>
	<%= f.file_field :rawfile %><br>
	<%= label_tag "Recipient's Email:" %><br>
	<%= select("recipient","recipient_id", @users.all.collect {|r| [ r.email, r.email ]}) %><br>
	<%= label_tag "Name of the Recipient's Public Key:" %><br>
	<%= text_field_tag :key_name %><br>
<%= f.button :submit, :class => "btn btn-xs btn-success" %>
<% end %>

app/views/safes/edit.html.erb
edit.html.erb

app/views/safes/index.html.erb
<div class="col-md-8">
<%= link_to "New Safe", new_safe_path, class: "btn btn-sm btn-success" %><p>
<table class="table table-bordered table-striped">
<tbody>
	<% @safes.each do |safe| %>
<tr>
	<td class="col-sm-2"><%= link_to(safe.name, safe) %></td>
	<td class="col-sm-6"><%= safe.description %></td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/safes/new.html.erb
<%= render 'form' %>

app/views/safes/show.html.erb
<% if current_user.id == @safe.user_id %>
<h3><%= @safe.name %></h3>
<div class="span4">
<h4>Encrypt a File</h4>
<%= render 'upload' %>
<p>
</div>
<div class="span4">
<h4>Decrypt a File</h4>
<%= render 'decrypt'%>
</div>
<%else%>
Not your safe homeboy.
<%end%>

app/views/users/index.html.erb
<div class="col-md-8">
<table class="table table-bordered table-striped">
<tbody>
	<% @users.each do |user| %>
<tr>
	<td class="col-sm-2"><%= link_to(user.email, user) %></td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/users/show.html.erb
<h3><%= @user.email %></h3><br>
<h2>Public Keys for <%= @user.email %></h2><p>
<table class="table table-bordered table-striped">
<tbody>
  <% @keys.each do |key| %>
<tr>
  <td class="col-sm-2"><%=link_to(key.name, key) %></td>
</tr>
<% end %>
</tbody>
</table>
</div>